title: RESTAutonomousPi
logo: RESTAutonomousPi/docs/thumbnail.png
description: A powerwheels jeep being ran off a Raspberry Pi 3, without any inputs
show_downloads: true
google_analytics: true
theme: jekyll-theme-minimal
